http:
  port: "8082"
  
transaction:
  sapi:
    host: "35.221.56.54"
    port: "8081"
    endpoint_paymentReference: "/api/payments/referenceId"
    endpoint_recordPayment: "/api/payments/paymentTransactions"
    endpoint_checkout: "/api/payments/checkouts"
    endpoint_exchangeRate: "/api/payments/exchangeRates"